name: Hele Adonis CI

on:
  pull_request:
    tags:
      - v*
    branches:
      - dev
      - master

jobs:
  # Lint testing job
  lint:
    name: "Lint testing"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node dev modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-dev-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys:
          ${{ runner.os }}-lint-${{ env.cache-name }}-
          ${{ runner.os }}-lint-
          ${{ runner.os }}-

    - name: Install Dev Dependencies
      run: npm install --dev

    - name: Run Lint Tests
      run: npm run lint
